<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Uuid\\' => array($vendorDir . '/symfony/polyfill-uuid'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'FG\\' => array($vendorDir . '/fgrosse/phpasn1/lib'),
    'Cose\\' => array($vendorDir . '/web-auth/cose-lib/src'),
    'CBOR\\' => array($vendorDir . '/spomky-labs/cbor-php/src'),
    'Brick\\Math\\' => array($vendorDir . '/brick/math/src'),
    'Assert\\' => array($vendorDir . '/beberlei/assert/lib/Assert'),
);
